flags:
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
packages:
- '.'
extra-deps:
- split-0.2.3.1
- json-0.9.1
- mtl-2.2.1
- random-1.1
- text-1.2.2.1
- happstack-server-7.4.6.2
- base64-bytestring-1.0.0.1
- blaze-html-0.8.1.2
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- hslogger-1.2.10
- html-1.0.1.2
- monad-control-1.0.1.0
- network-2.6.3.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- parsec-3.1.11
- sendfile-0.7.9
- syb-0.6
- system-filepath-0.4.13.4
- threads-0.5.1.4
- time-compat-0.1.0.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- utf8-string-1.0.1.1
- zlib-0.6.1.2
- blaze-builder-0.4.0.2
- blaze-markup-0.7.1.0
- old-time-1.1.0.3
- stm-2.4.4.1
- aeson-1.0.2.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- dlist-0.8.0.2
- fail-4.9.0.0
- hashable-1.2.4.0
- primitive-0.6.1.0
- scientific-0.3.4.9
- semigroups-0.18.2
- tagged-0.8.5
- time-locale-compat-0.1.1.3
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- HUnit-1.5.0.0
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- call-stack-0.1.0
- hostname-1.0
- regex-posix-0.95.2
- xml-1.3.14
- regex-base-0.93.2
- QuickCheck-2.9.2
- tf-random-0.5
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- async-2.1.1
- quickcheck-io-0.1.4
- setenv-0.1.1.3
resolver: ghc-7.10
